import { useMediaSource } from '../../../lib/hooks/use-media-source'
import { memo, useCallback, useMemo } from 'react'
import { AudioItem as AudioItemDto } from 'tapestry-core/src/data-format/schemas/item'
import { MediaPlayer, MediaPlayerProps, VideoJSOptions } from '../../../lib/media-player'
import { useTapestryConfig } from '../..'
import { useMediaParams } from '../../hooks/use-media-params'
import { Id } from 'tapestry-core/src/data-format/schemas/common'
import { setItemIsPlaying } from '../../../../view-model/store-commands/tapestry'

export interface AudioItemPlayerProps extends Partial<MediaPlayerProps<'audio'>> {
  id: Id
  mediaType?: string
}

export const AudioItemPlayer = memo(
  ({ id, mediaType, style, ...playerProps }: AudioItemPlayerProps) => {
    const { useStoreData, useDispatch } = useTapestryConfig()
    const dispatch = useDispatch()
    const { startTime, source, stopTime, thumbnail } = useStoreData(
      `items.${id}.dto`,
    ) as AudioItemDto
    const customThumbnail = thumbnail?.renditions.find(
      (r) => r.isPrimary && !r.isAutoGenerated,
    )?.source
    const src = useMediaSource(source)
    const mediaParams = useMediaParams(id)

    const onStart = useCallback(() => {
      dispatch(setItemIsPlaying(id, true))
    }, [dispatch, id])

    const onStop = useCallback(() => {
      dispatch(setItemIsPlaying(id, false))
    }, [dispatch, id])

    const options = useMemo<VideoJSOptions>(
      () => ({
        src,
        mediaType,
        controls: true,
        inactivityTimeout: 0,
        ...(customThumbnail ? { poster: customThumbnail, audioOnlyMode: false } : {}),
      }),
      [src, customThumbnail, mediaType],
    )

    return (
      <MediaPlayer
        id={id}
        component="audio"
        options={options}
        startTime={mediaParams.startTime ?? startTime ?? 0}
        stopTime={mediaParams.stopTime ?? stopTime ?? undefined}
        onPlay={onStart}
        onPause={onStop}
        onEnded={onStop}
        style={{ display: 'block', width: '100%', height: '100%', ...style }}
        {...playerProps}
      />
    )
  },
)
