import { useMediaSource } from '../../../lib/hooks/use-media-source'
import { memo, useCallback, useMemo, useRef, useState } from 'react'
import { VideoItem as VideoItemDto } from 'tapestry-core/src/data-format/schemas/item'
import { MediaPlayer, VideoJSOptions, MediaPlayerProps } from '../../../lib/media-player'
import { captureVideoFrame } from '../../../../lib/dom'
import { useMediaParams } from '../../hooks/use-media-params'
import { Id } from 'tapestry-core/src/data-format/schemas/common'
import { useTapestryConfig } from '../..'
import { IconOverlay } from '../../video-play-overlay'
import styles from './styles.module.css'
import { getPrimaryThumbnail } from '../../../../view-model/utils'
import { setItemIsPlaying } from '../../../../view-model/store-commands/tapestry'

export interface VideoItemPlayerProps extends Partial<MediaPlayerProps<'video'>> {
  id: Id
  mediaType?: string
}

export const VideoItemPlayer = memo(
  ({ id, mediaType, style, ...playerProps }: VideoItemPlayerProps) => {
    const { useStoreData, useDispatch } = useTapestryConfig()
    const dispatch = useDispatch()
    const dto = useStoreData(`items.${id}.dto`) as VideoItemDto
    const isInteractive = useStoreData('interactiveElement')?.modelId === id
    const src = useMediaSource(dto.source)
    const mediaParams = useMediaParams(id)

    const [isPlaying, setIsPlaying] = useState(false)
    const [thumbnail, setThumbnail] = useState(() => getPrimaryThumbnail(dto))
    const frameThumbnailRef = useRef<string>(undefined)

    const onStart = useCallback(() => {
      setIsPlaying(true)
      dispatch(setItemIsPlaying(id, true))
    }, [dispatch, id])

    const onStop = useCallback(() => {
      setIsPlaying(false)
      dispatch(setItemIsPlaying(id, false))
    }, [dispatch, id])

    const captureFrame = useCallback(
      async (media: HTMLVideoElement | HTMLAudioElement) => {
        // Return early if the element isn't a video element
        if (!(media instanceof HTMLVideoElement)) {
          return
        }

        const video = media
        const hasCustomThumbnail = dto.thumbnail?.renditions.find(
          (r) => r.isPrimary && !r.isAutoGenerated,
        )

        if (!video || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA || hasCustomThumbnail) {
          return
        }

        if (thumbnail && thumbnail === frameThumbnailRef.current) {
          URL.revokeObjectURL(thumbnail)
        }

        const blob = await captureVideoFrame(video)
        const url = URL.createObjectURL(blob)
        frameThumbnailRef.current = url
        setThumbnail(url)
      },
      [dto.thumbnail, thumbnail],
    )

    const options = useMemo<VideoJSOptions>(
      () => ({
        src,
        mediaType,
        controls: true,
        crossorigin: 'anonymous',
        preload: 'metadata',
      }),
      [src, mediaType],
    )

    return (
      <div className={styles.root}>
        <MediaPlayer
          component="video"
          options={options}
          startTime={mediaParams.startTime ?? dto.startTime ?? 0}
          stopTime={mediaParams.stopTime ?? dto.stopTime ?? undefined}
          onPlay={onStart}
          onPause={(e) => {
            onStop()
            void captureFrame(e.currentTarget)
          }}
          onEnded={onStop}
          onSeeked={(e) => {
            if (e.currentTarget.paused) {
              void captureFrame(e.currentTarget)
            }
          }}
          thumbnail={thumbnail}
          // The video is hidden in order to optimize the Safari layering algorithm
          //MediaPlayer handles display: none of the video
          style={{
            width: '100%',
            height: '100%',
            ...style,
          }}
          {...playerProps}
        />

        {!isInteractive && !isPlaying && <IconOverlay itemSize={dto.size} icon="videocam" />}
      </div>
    )
  },
)
